# 

name: Psalm Security Scan

# Controls when the workflow will run

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm – Security Scanner for PHP
        uses: psalm/psalm-github-security-scan@1.2.1
        
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
